-- Feed Fusion Tanzania — Migration 021 (2026-09-25, owner's request)
-- Adds a due date to a sale, for two related but distinct needs:
--
-- 1. "Kwa deni" (give on credit) — the owner wants to hand over goods for
--    TZS 0 collected right now (not a partial deposit), track it as a real
--    debt, and have it flagged "overdue" automatically once the date
--    passes. Credit sales already exist since migration 018 (a PARTIAL
--    sale with balance_due > 0) but always required a positive deposit —
--    BR-04, "no sale with no payment," stays intact for the ordinary sale
--    flow. A TZS-0 sale is only ever allowed through a new, deliberate
--    "Give on Credit" path (sales.service.ts completeSale) that requires
--    BOTH a linked customer (customer_id — not just a typed walk-in name)
--    and this due_date, so it can never happen by accident.
-- 2. A due date is also useful on an ordinary PARTIAL sale (a deposit now,
--    the rest promised by a date) — so this column isn't restricted to
--    TZS-0 sales specifically, it's just required for them.
--
-- Nullable: most sales (PAID in full, or PARTIAL with no agreed date) never
-- set this. "Overdue" is never stored — same derive-don't-store principle
-- as balance_due — always computed as due_date < today AND balance_due > 0
-- (see salesRepo.getOutstandingBalances).
ALTER TABLE sales ADD COLUMN due_date DATE;
